/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doannhom4_qlnh;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ad
 */
public class frmDangNhapUser extends javax.swing.JFrame {

    /**
     * Creates new form frmDangNhapUser
     */
    public frmDangNhapUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDNUser = new javax.swing.JButton();
        txtMkUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDNUser.setBackground(new java.awt.Color(0, 255, 102));
        btnDNUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDNUser.setForeground(new java.awt.Color(255, 255, 255));
        btnDNUser.setText("Đăng nhập");
        btnDNUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnDNUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 350, 50));
        getContentPane().add(txtMkUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 350, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật khẩu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 30));
        getContentPane().add(txtTenuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 350, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên đăng nhập");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/custom-login-form.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
QuanLyUser qlus = new QuanLyUser();
    private void btnDNUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNUserActionPerformed
        // TODO add your handling code here:
        ArrayList<User> nh = qlus.DocDuLieu("User.txt");
        for (User user : nh) {
            qlus.Them(user);
        }
        ArrayList<User> ad = qlus.getData();
        String tenDN = txtTenuser.getText();
        String matKhau = txtMkUser.getText();
        for (User user : ad) {
            if (tenDN.equals(user.getTenDangNhap()) && matKhau.equals(user.getMatKhau())) {
                new frmTrangThucDon().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập lại");
            }
        }
    }//GEN-LAST:event_btnDNUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhapUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhapUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhapUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhapUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangNhapUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDNUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMkUser;
    private javax.swing.JTextField txtTenuser;
    // End of variables declaration//GEN-END:variables
}
