/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doannhom4_qlnh;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class frmGioHang extends javax.swing.JFrame {

    /**
     * Creates new form frmGioHang
     */
    public frmGioHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMonAn = new javax.swing.JTable();
        txtTenMA = new javax.swing.JTextField();
        txtHinh = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaMA = new javax.swing.JTextField();
        txtThemGH = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenNM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtSDT1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Giỏ hàng");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 176, -1));

        jLabel2.setFont(new java.awt.Font("Zilla Slab Medium", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Restaurant Food");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        tableMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMonAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMonAn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 550, 190));

        txtTenMA.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(txtTenMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 157, -1));

        txtHinh.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(txtHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 157, -1));

        txtGia.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 157, -1));

        jLabel3.setText("Mã món ăn:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 10));

        jLabel4.setText("Tên món ăn:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 20));

        jLabel5.setText("Hình ảnh:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 10));

        jLabel6.setText("Tên người dùng (Bắt buộc)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        txtMaMA.setBackground(new java.awt.Color(0, 255, 204));
        txtMaMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMAActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 157, -1));

        txtThemGH.setBackground(new java.awt.Color(255, 255, 0));
        txtThemGH.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtThemGH.setText("Mua");
        txtThemGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemGHActionPerformed(evt);
            }
        });
        getContentPane().add(txtThemGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 100, 50));

        btnDoc.setBackground(new java.awt.Color(204, 0, 204));
        btnDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoc.setForeground(new java.awt.Color(153, 255, 255));
        btnDoc.setText("Xem DS giỏ hàng");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 180, 30));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 498, 37, -1));

        jLabel8.setText("Số điện thoại:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 655, -1, -1));

        txtTenNM.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(txtTenNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 157, -1));

        jLabel9.setText("Giá bán:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        btnThoat.setBackground(new java.awt.Color(255, 0, 51));
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        jLabel11.setText("Số điện thoại (Bắt buộc)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 20));

        txtSDT1.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(txtSDT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 157, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    QuanLyGioHang qlgh = new QuanLyGioHang();
    QuanLyThucDon qltd = new QuanLyThucDon();
    private void tableMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMonAnMouseClicked
        // TODO add your handling code here:
        int row = tableMonAn.getSelectedRow();
        ThucDon nh = qltd.getData().get(row);
        txtMaMA.setText(nh.getMaMonAn());
        txtTenMA.setText(nh.getTenMonAn());
        txtHinh.setText(nh.getHinh());
        txtGia.setText(String.valueOf(nh.getGiaBan()));
    }//GEN-LAST:event_tableMonAnMouseClicked

    private void txtMaMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMAActionPerformed

    private void txtThemGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemGHActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String maMA = txtMaMA.getText();
        String tenMA = txtTenMA.getText();
        String hinh = txtHinh.getText();
        int giaBan = Integer.parseInt(txtGia.getText());
        int sdt = Integer.parseInt(txtSDT1.getText());
         String tenNM = txtTenNM.getText();
        qlgh.ThemMonAn(new GioHang(maMA, tenMA, hinh, giaBan, sdt,tenNM));
        HienThi();
        qlgh.GhiDuLieu("DonHang.txt");
        
        JOptionPane.showMessageDialog(this, "Mua thành công !");
        
        boolean kt = qltd.Xoa(maMA);
        if (kt) {
            HienThi();

           
        } else {
            JOptionPane.showMessageDialog(this, "Không xóa được");
        }
        
    }//GEN-LAST:event_txtThemGHActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
          ArrayList<ThucDon> nh = qltd.DocDuLieu("GioHang.txt");
        for (ThucDon monAn : nh) {
            qltd.ThemMonAn(monAn);
        }
        HienThi();
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
       //new frmTrangThucDon().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

      private void HienThi() {
        DefaultTableModel tableModel = (DefaultTableModel) tableMonAn.getModel();
        tableModel.setColumnCount(0);
        tableModel.setRowCount(0);
        tableModel.addColumn("Mã món ăn");
        tableModel.addColumn("Tên món ăn");
        tableModel.addColumn("Hình");
        tableModel.addColumn("Giá bán");
        ArrayList<ThucDon> data = qltd.getData();
        for (ThucDon monAn : data) {
            tableModel.addRow(new Object[]{monAn.getMaMonAn(), monAn.getTenMonAn(), monAn.getHinh(), monAn.getGiaBan()});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGioHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMonAn;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtHinh;
    private javax.swing.JTextField txtMaMA;
    private javax.swing.JTextField txtSDT1;
    private javax.swing.JTextField txtTenMA;
    private javax.swing.JTextField txtTenNM;
    private javax.swing.JButton txtThemGH;
    // End of variables declaration//GEN-END:variables
}
