/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doannhom4_qlnh;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class frmTrangThucDon extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangThucDon
     */
    public frmTrangThucDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMonAn = new javax.swing.JTable();
        txtTenMA = new javax.swing.JTextField();
        txtHinh = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaMA = new javax.swing.JTextField();
        txtThemGH = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblanh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Thực đơn món ăn");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 176, -1));

        jLabel2.setFont(new java.awt.Font("Zilla Slab Medium", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Restaurant Food");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 16, -1, -1));

        tableMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMonAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMonAn);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 491, 190));

        txtTenMA.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(txtTenMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 197, 157, -1));

        txtHinh.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(txtHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 230, 157, -1));

        txtGia.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 264, 157, -1));

        jLabel3.setText("Mã món ăn:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 168, -1, -1));

        jLabel4.setText("Tên món ăn:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel5.setText("Hình ảnh:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 235, -1, -1));

        jLabel6.setText("Giá bán:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 269, -1, -1));

        txtMaMA.setBackground(new java.awt.Color(0, 255, 204));
        txtMaMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMAActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 161, 157, -1));

        txtThemGH.setBackground(new java.awt.Color(102, 255, 204));
        txtThemGH.setText("Thêm vào giỏ hàng");
        txtThemGH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThemGHActionPerformed(evt);
            }
        });
        getContentPane().add(txtThemGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, 50));

        jButton2.setBackground(new java.awt.Color(102, 255, 204));
        jButton2.setText("Giỏ hàng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 40));

        btnDoc.setBackground(new java.awt.Color(204, 0, 204));
        btnDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoc.setForeground(new java.awt.Color(153, 255, 255));
        btnDoc.setText("Xem DS Thực đơn");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 443, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 220, 200));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 220, 200));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 220, 200));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 220, 200));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, 200));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 220, 200));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repeat.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 220, 200));

        lblanh.setText("Ảnh");
        getContentPane().add(lblanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    QuanLyMonAn qlnh = new QuanLyMonAn();
    QuanLyThucDon qltd = new QuanLyThucDon();
    private void tableMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMonAnMouseClicked
        // TODO add your handling code here:
        int row = tableMonAn.getSelectedRow();
        MonAn nh = qlnh.getData().get(row);
        txtMaMA.setText(nh.getMaMonAn());
        txtTenMA.setText(nh.getTenMonAn());
        lblanh.setIcon(new ImageIcon(getClass().getResource("/img/"+nh.getHinh())));
        txtGia.setText(String.valueOf(nh.getGiaBan()));
    }//GEN-LAST:event_tableMonAnMouseClicked

    private void txtMaMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMAActionPerformed

    private void txtThemGHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThemGHActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        String maMA = txtMaMA.getText();
        String tenMA = txtTenMA.getText();
        String hinh = txtHinh.getText();
        int giaBan = Integer.parseInt(txtGia.getText());
        qltd.ThemMonAn(new ThucDon(maMA, tenMA, hinh, giaBan));
        HienThi();
         qltd.GhiDuLieu("GioHang.txt");
        JOptionPane.showMessageDialog(this, "Thêm thành công !");
        
    }//GEN-LAST:event_txtThemGHActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
        ArrayList<MonAn> nh = qlnh.DocDuLieu("MonAn.txt");
        for (MonAn monAn : nh) {
            qlnh.ThemMonAn(monAn);
        }
        HienThi();
    }//GEN-LAST:event_btnDocActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new frmGioHang().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

     private void HienThi() {
        DefaultTableModel tableModel = (DefaultTableModel) tableMonAn.getModel();
        tableModel.setColumnCount(0);
        tableModel.setRowCount(0);
        tableModel.addColumn("Mã món ăn");
        tableModel.addColumn("Tên món ăn");
        tableModel.addColumn("Hình");
        tableModel.addColumn("Giá bán");
        ArrayList<MonAn> data = qlnh.getData();
        for (MonAn monAn : data) {
            tableModel.addRow(new Object[]{monAn.getMaMonAn(), monAn.getTenMonAn(), monAn.getHinh(), monAn.getGiaBan()});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangThucDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangThucDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblanh;
    private javax.swing.JTable tableMonAn;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtHinh;
    private javax.swing.JTextField txtMaMA;
    private javax.swing.JTextField txtTenMA;
    private javax.swing.JButton txtThemGH;
    // End of variables declaration//GEN-END:variables
}
