/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doannhom4_qlnh;

/**
 *
 * @author Asus
 */
public class frmTrangQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangQuanLy
     */
    public frmTrangQuanLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnQuanLyMonAn1 = new javax.swing.JToggleButton();
        btnQuanLyMonAn2 = new javax.swing.JToggleButton();
        btnQuanLyMonAn3 = new javax.swing.JToggleButton();
        btnQuanLyMonAn4 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Zilla Slab Medium", 1, 36)); // NOI18N
        jLabel2.setText("Restaurant Food");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        btnQuanLyMonAn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyMonAn1.setText("Quản lý món ăn");
        btnQuanLyMonAn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonAn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuanLyMonAn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 79, 148, 42));

        btnQuanLyMonAn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyMonAn2.setText("Quản lý nhân viên");
        btnQuanLyMonAn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonAn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuanLyMonAn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, 42));

        btnQuanLyMonAn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyMonAn3.setText("Quản lý doanh thu");
        btnQuanLyMonAn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonAn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuanLyMonAn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 42));

        btnQuanLyMonAn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuanLyMonAn4.setText("Quản lý đơn hàng");
        btnQuanLyMonAn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyMonAn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuanLyMonAn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 42));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanli.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 200));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanli.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanli.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quanli.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 210, 200));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Đăng Xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyMonAn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonAn1ActionPerformed
        // TODO add your handling code here:
        new frmQuanLyMonAn().setVisible(true);
    }//GEN-LAST:event_btnQuanLyMonAn1ActionPerformed

    private void btnQuanLyMonAn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonAn2ActionPerformed
        // TODO add your handling code here:
        new frmQuanLyNhanVien().setVisible(true);
        
    }//GEN-LAST:event_btnQuanLyMonAn2ActionPerformed

    private void btnQuanLyMonAn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonAn3ActionPerformed
        // TODO add your handling code here:
        new frmDoanhThu().setVisible(true);
        
    }//GEN-LAST:event_btnQuanLyMonAn3ActionPerformed

    private void btnQuanLyMonAn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyMonAn4ActionPerformed
        // TODO add your handling code here:
        new frmDonHang().setVisible(true);
        
    }//GEN-LAST:event_btnQuanLyMonAn4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new frmDangNhap().setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnQuanLyMonAn1;
    private javax.swing.JToggleButton btnQuanLyMonAn2;
    private javax.swing.JToggleButton btnQuanLyMonAn3;
    private javax.swing.JToggleButton btnQuanLyMonAn4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
